# Generated by Django 4.1.2 on 2023-06-06 23:28

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=pathlib.PureWindowsPath('profile_images/default_male.jpg'), upload_to='profile_images/'),
        ),
    ]
